version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pluxity
      SPRING_DATASOURCE_USERNAME: pluxity
      SPRING_DATASOURCE_PASSWORD: pluxity123!@#
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pluxity123!@#
      MYSQL_DATABASE: pluxity
      MYSQL_USER: pluxity
      MYSQL_PASSWORD: pluxity123!@#
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 30s

volumes:
  db_data:

networks:
  app-network: