
services:
  plug-platform-postgres:
    image: postgres:15
    container_name: postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pluxity
      - POSTGRES_PASSWORD=pluxity0304
      - POSTGRES_DB=plug_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # PostgreSQL 공식 이미지는 자체 healthcheck 스크립트가 있음
      test: ["CMD-SHELL", "pg_isready -U pluxity -d plug_db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # networks:
    #   - default

  redis:
    image: redis:latest # 또는 redis:alpine 등 특정 버전
    container_name: redis-local
    ports:
      - "6379:6379"
    # volumes: # Redis 데이터 영속화가 필요하다면
    #   - redis_data:/data
    healthcheck: # Redis healthcheck 추가
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5 # API가 의존하므로 retries 증가
    restart: unless-stopped
    # networks:
    #   - default

  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z-cpuv1
    container_name: minio-local
    ports:
      - "9000:9000" # 데이터 API 포트
      - "9001:9001" # 콘솔 포트
    environment:
      MINIO_ROOT_USER: pluxity
      MINIO_ROOT_PASSWORD: pluxity0304

    volumes:
      - minio_data:/data # 명명된 볼륨 사용 권장
    command: server /data --console-address ":9001"
    healthcheck: # MinIO healthcheck (간단한 예시, 더 정교하게 만들 수 있음)
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped