spring:
  application:
    name: plug-platform
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/pluxity;
    username: pluxity
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        envers:
          store_data_at_delete: true
        format_sql: true

logging:
  level:
    org: INFO
    com: DEBUG
    root: INFO