services:
  app:
    build:
      context: ..
      dockerfile: core/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=stage,common
      - DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/plugdb?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      - DATASOURCE_USERNAME=pluxity
      - DATASOURCE_PASSWORD=pluxity123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=host.docker.internal
      - SPRING_DATA_REDIS_PORT=6379
      - SERVER_PORT=8080
      - FILE_STORAGE_STRATEGY=local
      - FILE_UPLOAD_PATH=/app/upload/
    ports:
      - "8080:8080"
    volumes:
      - upload:/app/upload
    restart: unless-stopped
    networks:
      - plug-network

volumes:
  upload:

networks:
  plug-network:
    driver: bridge 