version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: core/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-stage}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mariadb:3306/plugdb
      - SPRING_DATASOURCE_USERNAME=plug
      - SPRING_DATASOURCE_PASSWORD=plug123!@#
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    volumes:
      - upload:/app/upload

  mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=root123!@#
      - MYSQL_DATABASE=plugdb
      - MYSQL_USER=plug
      - MYSQL_PASSWORD=plug123!@#
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  upload: 