spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/plug_db
    username: ${DB_USERNAME:pluxity}
    password: ${DB_PASSWORD:pluxity0304}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 5
  flyway:
    enabled: false
