spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 1000
  application:
    name: plug-platform-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:plug-platform-postgres}:${DB_PORT:5432}/plug_db
    username: ${DB_USERNAME:pluxity}
    password: ${DB_PASSWORD:pluxity0304}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  flyway:
    enabled: false

file:
  storage-strategy: ${FILE_STORAGE_STRATEGY:s3}
  local:
    path: ${FILE_LOCAL_PATH:/app/upload}
  s3:
    endpoint-url: http://192.168.4.20:9000
    public-url: http://api.plug-platform.com:9000
    bucket: ${S3_BUCKET:plug-platform}
    region: ${S3_REGION:ap-northeast-2}
    access-key: ${S3_ACCESS_KEY:pluxity}
    secret-key: ${S3_SECRET_KEY:pluxity0304}
    pre-signed-url-expiration: 600

logging:
  level:
    org: INFO
    com: INFO
    root: INFO
    # SQL 쿼리를 보여주는 로거
#    org.hibernate.SQL: DEBUG
    # 바인딩되는 파라미터(?에 들어가는 값)를 보여주는 로거
#    org.hibernate.orm.jdbc.bind: TRACE


