spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  application:
    name: core
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

file:
  storage-strategy: s3
  local:
    path: C:/Dev/Upload/
  s3:
    #    endpoint-url: http://127.0.0.1:9000
    external-url-prefix: http://192.168.4.29:9000
    bucket: plug-platform
    region: ap-northeast-2
    access-key: pluxity
    secret-key: pluxity0304
    pre-signed-url-expiration: 600

domain:
  name: localhost

logging:
  level:
    org: INFO
    com: DEBUG
    root: INFO

cloud:
  aws:
    s3:
      endpoint: http://192.168.4.29:9000
      credentials:
        access-key: ${S3_ACCESS_KEY:pluxity}
        secret-key: ${S3_SECRET_KEY:pluxity0304}
      region:
        static: ${S3_REGION:ap-northeast-2} # MinIO는 리전이 중요하지 않으나 SDK는 요구
      path-style-access-enabled: true      # MinIO 사용 시 true 권장