spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 1000
  application:
    name: plug-platform-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:plug-platform-postgres}:${DB_PORT:5432}/plug_db
    username: ${DB_USERNAME:pluxity}
    password: ${DB_PASSWORD:pluxity0304}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  flyway:
    enabled: false

logging:
  level:
    org: INFO
    com: INFO
    root: INFO 