facility:
  station:
    enabled: true
  building:
    enabled: false

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    group:
      default: common, local
      local: common, local
      stage: common, stage
      prod: common, prod
  flyway:
    enabled: false