spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=LEGACY # WARN: MODE=LEGACY를 사용하지 않으면 ACL이 h2에서 정상적으로 동작하지 않는다
    username: pluxity
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  flyway:
    enabled: false

file:
  storage-strategy: s3
  local:
    path: C:/Dev/Upload/
  s3:
    #    endpoint-url: http://127.0.0.1:9000
    endpoint-url: http://192.168.4.34:9000
    bucket: plug-platform
    region: ap-northeast-2
    access-key: pluxity
    secret-key: pluxity0304
    pre-signed-url-expiration: 600

domain:
  name: plug-platform.com

logging:
  level:
    org: INFO
    com: DEBUG
    root: INFO


jwt:
  access-token:
    name: AccessToken
    secret: +iBcUJRWGvl+94+ow4nXV1fzWIq4rph8x7MyRmrtWio=
    expiration: 3600
  refresh-token:
    name: RefreshToken
    secret: gtzRlqF6bIkmOi5i15A9G5xbLdwiAMmZi6JPOeemC1E=
    expiration: 86400

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
  packages-to-scan: com.pluxity
  default-consumes-media-type: application/json
  default-produces-media-type: application/json