spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: pluxity
    password: pluxity0304
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

file:
  storage-strategy: s3
  local:
    path: C:/Dev/Upload/
  s3:
    endpoint-url: http://192.168.4.29:9000
    public-url: http://192.168.4.29:9000
    bucket: plug-platform
    region: ap-northeast-2
    access-key: pluxity
    secret-key: pluxity0304
    pre-signed-url-expiration: 600

domain:
  name: localhost

logging:
  level:
    org: INFO
    com: DEBUG
    root: INFO

