spring:
  data:
    redis:
      host: ${REDIS_HOST:plug-platform-redis}
      port: ${REDIS_PORT:6379}
      timeout: 1000
  application:
    name: plug-platform-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:plug-platform-postgres}:${DB_PORT:5432}/plug_db
    username: ${DB_USERNAME:pluxity}
    password: ${DB_PASSWORD:pluxity0304}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

file:
  storage-strategy: ${FILE_STORAGE_STRATEGY:s3}
  local:
    path: ${FILE_LOCAL_PATH:/app/upload}
  s3:
    external-url-prefix: ${MINIO_EXTERNAL_FILE_URL_PREFIX:http://localhost/files}
    bucket: ${S3_BUCKET:plug-platform}
    region: ${S3_REGION:ap-northeast-2}
    access-key: ${S3_ACCESS_KEY:pluxity}
    secret-key: ${S3_SECRET_KEY:pluxity0304}
    pre-signed-url-expiration: 600

cloud:
  aws:
    s3:
      endpoint: ${S3_INTERNAL_ENDPOINT_URL:http://minio:9000} # API 서버 -> MinIO 서버 내부 통신용
      credentials:
        access-key: ${S3_ACCESS_KEY:pluxity}
        secret-key: ${S3_SECRET_KEY:pluxity0304}
      region:
        static: ${S3_REGION:ap-northeast-2} # MinIO는 리전이 중요하지 않으나 SDK는 요구
      path-style-access-enabled: true      # MinIO 사용 시 true 권장


domain:
  name: ${DOMAIN_NAME:localhost}


logging:
  level:
    org: INFO
    com: INFO
    root: INFO