spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  show-actuator: true
  packages-to-scan: com.pluxity
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  info:
    title: Plug Platform API
    description: Plug Platform API Documentation
    version: 1.0.0
    contact:
      name: Pluxity
      email: support@pluxity.com
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

file:
  storage-strategy: s3
  upload:
    path: /app/upload/
    temp-dir: /app/upload/temp/ 