server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
#  address: ${SERVER_ADDRESS:0.0.0.0}

domain:
  name: pluxity.com

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
jwt:
  access-token:
    name: AccessToken
    secret: +iBcUJRWGvl+94+ow4nXV1fzWIq4rph8x7MyRmrtWio=
    expiration: 36000000
  refresh-token:
    name: RefreshToken
    secret: gtzRlqF6bIkmOi5i15A9G5xbLdwiAMmZi6JPOeemC1E=
    expiration: 864000000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
  packages-to-scan: com.pluxity
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logbook:
  obfuscate: # 민감 정보 마스킹 가능
    headers:
      - Cookie
      - Set-Cookie
    json-body-fields:
      - password
  predicate:
    exclude:
      - path: /actuator/**
      - path: /swagger-ui/**
      - path: /api-docs/**
      - path: /.well-known/**

tcp:
  server1: 101.254.21.100
  server2: 101.254.21.100
  server3: 101.254.21.100
  server4: 101.254.21.100
  port1: 4001
  port2: 4002
  port3: 4003
  port4: 4004