server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
#  address: ${SERVER_ADDRESS:0.0.0.0}

domain:
  name: plug-platform.com

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    properties:
      hibernate:
        format_sql: true
jwt:
  access-token:
    name: AccessToken
    secret: +iBcUJRWGvl+94+ow4nXV1fzWIq4rph8x7MyRmrtWio=
    expiration: 36000000
  refresh-token:
    name: RefreshToken
    secret: gtzRlqF6bIkmOi5i15A9G5xbLdwiAMmZi6JPOeemC1E=
    expiration: 864000000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
  packages-to-scan: com.pluxity
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

tcp:
  server1: 101.254.21.100
  server2: 101.254.21.100:4002
  server3: 101.254.21.100:4003
  server4: 101.254.21.100:4004
  port1: 4001

cloud:
  aws:
    s3:
      endpoint: http://192.168.4.29:9000
      credentials:
        access-key: ${S3_ACCESS_KEY:pluxity}
        secret-key: ${S3_SECRET_KEY:pluxity0304}
      region:
        static: ${S3_REGION:ap-northeast-2} # MinIO는 리전이 중요하지 않으나 SDK는 요구
      path-style-access-enabled: true      # MinIO 사용 시 true 권장
