spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

file:
  storage-strategy: local  # local, s3
  upload:
    path: C:/Dev/Upload/
    temp-dir: C:/Dev/Upload/temp/
  s3:
    endpoint-url: http://192.168.4.56:9000
    bucket: plug-platform
    region: ap-northeast-2
    access-key: pluxity
    secret-key: pluxity123!@#
    pre-signed-url-expiration: 600

jwt:
  access-token:
    secret: +iBcUJRWGvl+94+ow4nXV1fzWIq4rph8x7MyRmrtWio=
    expiration: 3600000
  refresh-token:
    secret: gtzRlqF6bIkmOi5i15A9G5xbLdwiAMmZi6JPOeemC1E=
    expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  show-actuator: true
  packages-to-scan: com.pluxity
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  info:
    title: Plug Platform API
    description: Plug Platform API Documentation
    version: 1.0.0
    contact:
      name: Pluxity
      email: support@pluxity.com
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html