spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

file:
  storage-strategy: local
  upload:
    path: C:\Dev\Upload\
  s3:
    endpoint-url: http://192.168.4.56:9000
    bucket: plug-platform
    region: ap-northeast-2
    access-key: pluxity
    secret-key: pluxity123!@#
    pre-signed-url-expiration: 600

jwt:
  access-token:
    secret: +iBcUJRWGvl+94+ow4nXV1fzWIq4rph8x7MyRmrtWio=
    expiration: 3600000
  refresh-token:
    secret: gtzRlqF6bIkmOi5i15A9G5xbLdwiAMmZi6JPOeemC1E=
    expiration: 86400000