spring:
  profiles:
    group:
      default: common, local
      local: common, local
      stage: stage, common
      prod: common, prod
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    table: flyway_schema_history
    validate-on-migrate: true

logging:
  level:
    org: INFO
    com: INFO
    root: INFO
    org.zalando.logbook: TRACE