spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: pluxity
    password: pluxity0304
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  flyway:
    enabled: false

file:
  storage-strategy: s3
  local:
    path: C:/Dev/Upload/
  s3:
#    endpoint-url: http://127.0.0.1:9000
    endpoint-url: ${S3_ENDPOINT_URL:http://192.168.4.8:9000}
    public-url: ${S3_PUBLIC_URL:http://192.168.4.8:9000}
    bucket: plug-platform
    region: ap-northeast-2
    access-key: pluxity
    secret-key: pluxity0304
    pre-signed-url-expiration: 600

logging:
  level:
    com: DEBUG