server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  config:
    activate:
      on-profile: local
  application:
    name: core
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:tcp://localhost/~/pluxity}
    username: ${DATASOURCE_USERNAME:pluxity}
    password: ${DATASOURCE_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

file:
  storage-strategy: local
  upload:
    path: C:/Dev/Upload/

logging:
  level:
    org: INFO
    com: DEBUG
    root: INFO