server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  config:
    activate:
      on-profile: stage
  application:
    name: core
  datasource:
    url: jdbc:mysql://mariadb:3306/plugdb
    username: plug
    password: plug123!@#
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

file:
  storage-strategy: s3
  upload:
    path: /app/upload/
    temp-dir: /app/upload/temp/
  s3:
    endpoint-url: http://192.168.4.56:9000
    bucket: plug-platform
    region: ap-northeast-2
    access-key: pluxity
    secret-key: pluxity123!@#
    pre-signed-url-expiration: 600

logging:
  level:
    org: INFO
    com: INFO
    root: INFO 