server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: core
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://mariadb:3306/plugdb}
    username: ${DATASOURCE_USERNAME:plug}
    password: ${DATASOURCE_PASSWORD:plug123!@#}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

file:
  storage-strategy: s3
  upload:
    path: ${FILE_UPLOAD_PATH:/app/upload/}

logging:
  level:
    org: INFO
    com: INFO
    root: INFO 