# Stage 1: Build the project
FROM eclipse-temurin:21-jdk-alpine AS builder

RUN apk add --no-cache dos2unix

# Add Pinpoint
RUN wget https://repo1.maven.org/maven2/com/navercorp/pinpoint/pinpoint-agent/3.0.3/pinpoint-agent-3.0.3.tar.gz -O - | tar -xz -C /usr/local && \
    sed -i 's/profiler.transport.grpc.collector.ip=127.0.0.1/profiler.transport.grpc.collector.ip=192.168.4.8/g' /usr/local/pinpoint-agent-3.0.3/pinpoint-root.config && \
    sed -i 's/profiler.collector.ip=127.0.0.1/profiler.collector.ip=192.168.4.8/g' /usr/local/pinpoint-agent-3.0.3/pinpoint-root.config && \
    sed -i 's#profiler.server.excludeurl=#profiler.server.excludeurl=/actuator,/actuator/**,/swagger-ui/**,/api-docs/**#g' /usr/local/pinpoint-agent-3.0.3/pinpoint-root.config

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project to the container
COPY ../ .

RUN dos2unix ./gradlew

# Grant execution permission to the Gradle wrapper
RUN chmod +x ./gradlew

# Build the core module (and its dependencies, including common)
RUN ./gradlew spotlessApply
RUN ./gradlew clean build -x test --no-daemon

# Stage 2: Runtime image
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Pinpoint agent 복사
COPY --from=builder /usr/local/pinpoint-agent-3.0.3 /usr/local/pinpoint-agent-3.0.3

RUN chown -R 1000:1000 /usr/local/pinpoint-agent-3.0.3/logs

# Copy the built JAR file from the builder stage
COPY --from=builder /app/gs/build/libs/*.jar app.jar

# Expose port 8080 (or adjust to your app's port)
EXPOSE 8080

# Set the command to run the application
ENTRYPOINT ["java","-jar", \
"-javaagent:/usr/local/pinpoint-agent-3.0.3/pinpoint-bootstrap-3.0.3.jar", \
"-Dpinpoint.applicationName=plug_platform", \
"-Dpinpoint.config=/usr/local/pinpoint-agent-3.0.3/pinpoint-root.config", \
"app.jar"]