name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/plug-platform-api:latest

  deploy:
    name: 개발서버 배포
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.WINDOWS_SERVER_SSH_KEY }}

      - name: Test SSH connection with debug
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{secrets.WINDOWS_SERVER_USER}}@${{secrets.WINDOWS_SERVER_HOST}} echo "Debugging SSH"

      - name: Deploy to Windows Server
        run: |
          docker pull plug-platform-api:latest
          docker stop plug-platform-api || true
          docker rm plug-platform-api || true
          docker run -d --name plug-platform-api -p 18080:8080 plug-platform-api:latest
          EOF