name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/plug-platform-api:latest

  deploy:
    name: 개발서버 배포
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WINDOWS_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          
      - name: Debug SSH connection
        run: |
          echo "Testing SSH connection with verbose output..."
          ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.WINDOWS_SERVER_USER }}@${{ secrets.WINDOWS_SERVER_HOST }} "echo 'SSH connection test'"

      - name: Deploy to Windows Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.WINDOWS_SERVER_USER }}@${{ secrets.WINDOWS_SERVER_HOST }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/plug-platform-api:latest
            docker stop plug-platform-api || true
            docker rm plug-platform-api || true
            docker run -d --name plug-platform-api -p 18080:8080 ${{ secrets.DOCKER_USERNAME }}/plug-platform-api:latest
          "